# <font color="red">EXHAUSTIVE FEATURE SELECTION

In [1]:
import pandas as pd
from mlxtend.feature_selection import SequentialFeatureSelector

In [2]:
df=pd.read_csv(r"C:\Users\mitra\Desktop\MAIN\MITRA P\ML\ML TECHNIQUES\FEATURE SELECTION\COMMONLY USED METHOD\Iris (1).csv")

In [3]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
df.shape

(150, 6)

In [5]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [6]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [Id, SepalLengthCm, SepalWidthCm, PetalLengthCm, PetalWidthCm, Species]
Index: []

In [7]:
x=df.iloc[:,0:5]
y=df.iloc[:,-1]

In [8]:
x.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0   1            5.1           3.5            1.4           0.2
1   2            4.9           3.0            1.4           0.2
2   3            4.7           3.2            1.3           0.2
3   4            4.6           3.1            1.5           0.2
4   5            5.0           3.6            1.4           0.2

In [9]:
x.shape

(150, 5)

In [10]:
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

###  <font color="green">Spilt the X & y

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

In [12]:
from sklearn.ensemble import RandomForestClassifier

###

In [13]:
from mlxtend.feature_selection import ExhaustiveFeatureSelector  # Import Exhaustive Feature Selection

In [14]:
efs=ExhaustiveFeatureSelector(RandomForestClassifier(n_jobs=-1),           # All the courses availabe in your pc.
                                                   min_features=1,         # How many minimum feature you want to fit the model.    
                                                   max_features=5,         # How many maximum feature you want to fit the model.
                                                   scoring="accuracy",  
                                                   cv=2,
                                                   n_jobs=-1).fit(x_train,y_train)

Features: 31/31

In [15]:
efs.best_feature_names_

('Id', 'PetalLengthCm')

In [16]:
efs.best_score_

1.0

In [17]:
pd.DataFrame.from_dict(efs.get_metric_dict()).T

,feature_idx,cv_scores,avg_score,feature_names,ci_bound,std_dev,std_err
0,"(0,)","[0.9433962264150944, 1.0]",0.971698,"(Id,)",0.121773,0.028302,0.028302
1,"(1,)","[0.6415094339622641, 0.7115384615384616]",0.676524,"(SepalLengthCm,)",0.150655,0.035015,0.035015
2,"(2,)","[0.5094339622641509, 0.5384615384615384]",0.523948,"(SepalWidthCm,)",0.062448,0.014514,0.014514
3,"(3,)","[0.9245283018867925, 0.9423076923076923]",0.933418,"(PetalLengthCm,)",0.038249,0.00889,0.00889
4,"(4,)","[0.9056603773584906, 0.9423076923076923]",0.923984,"(PetalWidthCm,)",0.07884,0.018324,0.018324
5,"(0, 1)","[0.9622641509433962, 1.0]",0.981132,"(Id, SepalLengthCm)",0.081182,0.018868,0.018868
6,"(0, 2)","[0.9056603773584906, 0.9807692307692307]",0.943215,"(Id, SepalWidthCm)",0.161584,0.037554,0.037554
7,"(0, 3)","[1.0, 1.0]",1.0,"(Id, PetalLengthCm)",0.0,0.0,0.0
8,"(0, 4)","[1.0, 1.0]",1.0,"(Id, PetalWidthCm)",0.0,0.0,0.0
9,"(1, 2)","[0.6415094339622641, 0.7115384615384616]",0.676524,"(SepalLengthCm, SepalWidthCm)",0.150655,0.035015,0.035015
10,"(1, 3)","[0.9433962264150944, 0.9423076923076923]",0.942852,"(SepalLengthCm, PetalLengthCm)",0.002342,0.000544,0.000544
11,"(1, 4)","[0.9245283018867925, 0.9230769230769231]",0.923803,"(SepalLengthCm, PetalWidthCm)",0.003122,0.000726,0.000726
12,"(2, 3)","[0.9056603773584906, 0.9423076923076923]",0.923984,"(SepalWidthCm, PetalLengthCm)",0.07884,0.018324,0.018324
13,"(2, 4)","[0.8679245283018868, 0.9230769230769231]",0.895501,"(SepalWidthCm, PetalWidthCm)",0.118651,0.027576,0.027576
14,"(3, 4)","[0.9245283018867925, 0.9615384615384616]",0.943033,"(PetalLengthCm, PetalWidthCm)",0.079621,0.018505,0.018505
15,"(0, 1, 2)","[0.9622641509433962, 1.0]",0.981132,"(Id, SepalLengthCm, SepalWidthCm)",0.081182,0.018868,0.018868
16,"(0, 1, 3)","[0.9811320754716981, 0.9807692307692307]",0.980951,"(Id, SepalLengthCm, PetalLengthCm)",0.000781,0.000181,0.000181
17,"(0, 1, 4)","[0.9811320754716981, 1.0]",0.990566,"(Id, SepalLengthCm, PetalWidthCm)",0.040591,0.009434,0.009434
18,"(0, 2, 3)","[0.9811320754716981, 1.0]",0.990566,"(Id, SepalWidthCm, PetalLengthCm)",0.040591,0.009434,0.009434
19,"(0, 2, 4)","[1.0, 1.0]",1.0,"(Id, SepalWidthCm, PetalWidthCm)",0.0,0.0,0.0
20,"(0, 3, 4)","[0.9811320754716981, 0.9615384615384616]",0.971335,"(Id, PetalLengthCm, PetalWidthCm)",0.042152,0.009797,0.009797
21,"(1, 2, 3)","[0.9433962264150944, 0.9423076923076923]",0.942852,"(SepalLengthCm, SepalWidthCm, PetalLengthCm)",0.002342,0.000544,0.000544
22,"(1, 2, 4)","[0.8867924528301887, 0.9230769230769231]",0.904935,"(SepalLengthCm, SepalWidthCm, PetalWidthCm)",0.07806,0.018142,0.018142
23,"(1, 3, 4)","[0.9433962264150944, 0.9423076923076923]",0.942852,"(SepalLengthCm, PetalLengthCm, PetalWidthCm)",0.002342,0.000544,0.000544
24,"(2, 3, 4)","[0.9433962264150944, 0.9423076923076923]",0.942852,"(SepalWidthCm, PetalLengthCm, PetalWidthCm)",0.002342,0.000544,0.000544
25,"(0, 1, 2, 3)","[1.0, 1.0]",1.0,"(Id, SepalLengthCm, SepalWidthCm, PetalLengthCm)",0.0,0.0,0.0
26,"(0, 1, 2, 4)","[1.0, 1.0]",1.0,"(Id, SepalLengthCm, SepalWidthCm, PetalWidthCm)",0.0,0.0,0.0
27,"(0, 1, 3, 4)","[1.0, 1.0]",1.0,"(Id, SepalLengthCm, PetalLengthCm, PetalWidthCm)",0.0,0.0,0.0
28,"(0, 2, 3, 4)","[1.0, 1.0]",1.0,"(Id, SepalWidthCm, PetalLengthCm, PetalWidthCm)",0.0,0.0,0.0
29,"(1, 2, 3, 4)","[0.9433962264150944, 0.9615384615384616]",0.952467,"(SepalLengthCm, SepalWidthCm, PetalLengthCm, P...",0.03903,0.009071,0.009071
30,"(0, 1, 2, 3, 4)","[1.0, 0.9807692307692307]",0.990385,"(Id, SepalLengthCm, SepalWidthCm, PetalLengthC...",0.041372,0.009615,0.009615